### PR TITLE
Avoid a deprecation warning

### PR DESCRIPTION
**Pull request by gforcada**

### CODE REVIEW

**Comment by gforcada** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@gforcada any idea why mr.roboto/jenkins does not come up here?

**Comment by gforcada** [comment]
No idea, I will try to have a look at night

**Comment by gforcada** [comment]
testing mr.roboto...

**Comment by gforcada** [comment]
Oh I see, that's github being *dumb* :sweat_smile: I rebased my commits so the actual order displayed here in the pull request (which is always chronological) is not the same as if you do `git log` locally.

As we are attaching the statuses to the last commit, but github has its own definition of the last commit, you don't have the status here...

I think though, that if you start the jenkins jobs (@jenkins-plone-org please run jobs) it will work anyway.

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Pull request closed without merging**
