### PR TITLE
Fixes #76 - Restapi Fields vocabulary

### LINKED ISSUE #76: Can get the "Fields" vocabulary via plone.restapi
```
GET http://localhost:8080/Plone/@vocabularies/Fields
```

```
2020-05-27 20:27:57,382 ERROR   [waitress:356][waitress] Exception while serving /Plone/@vocabularies/Fields                                                                                  
Traceback (most recent call last):                                                                                                                                                            
  File "/joint/backend/eea-dx-cpanel-metadata/eggs/waitress-1.4.2-py3.8.egg/waitress/channel.py", line 349, in service                                                                        
    task.service()                                                                                                                                                                            
  File "/joint/backend/eea-dx-cpanel-metadata/eggs/waitress-1.4.2-py3.8.egg/waitress/task.py", line 169, in service                                                                           
    self.execute()                                                                                                                                                                            
  File "/joint/backend/eea-dx-cpanel-metadata/eggs/waitress-1.4.2-py3.8.egg/waitress/task.py", line 439, in execute                                                                           
    app_iter = self.channel.server.application(environ, start_response)                                                                                                                       
  File "/joint/backend/eea-dx-cpanel-metadata/eggs/Paste-3.1.1-py3.8.egg/paste/translogger.py", line 69, in __call__                                                                          
    return self.application(environ, replacement_start_response)                                                                                                                              
  File "/joint/backend/eea-dx-cpanel-metadata/eggs/Zope-4.1.3-py3.8.egg/ZPublisher/httpexceptions.py", line 30, in __call__                                                                   
    return self.application(environ, start_response)                                                                                                                                          
  File "/joint/backend/eea-dx-cpanel-metadata/eggs/Zope-4.1.3-py3.8.egg/ZPublisher/WSGIPublisher.py", line 338, in publish_module                                                             
    response = _publish(request, new_mod_info)                                                                                                                                                
  File "/joint/backend/eea-dx-cpanel-metadata/eggs/Zope-4.1.3-py3.8.egg/ZPublisher/WSGIPublisher.py", line 248, in publish                                                                    
    result = mapply(obj,                                                                                                                                                                      
  File "/joint/backend/eea-dx-cpanel-metadata/eggs/Zope-4.1.3-py3.8.egg/ZPublisher/mapply.py", line 85, in mapply                                                                             
    return debug(object, args, context)
  File "/joint/backend/eea-dx-cpanel-metadata/eggs/Zope-4.1.3-py3.8.egg/ZPublisher/WSGIPublisher.py", line 62, in call_object
    return obj(*args)
  File "/joint/backend/eea-dx-cpanel-metadata/eggs/plone.rest-1.6.0-py3.8.egg/plone/rest/service.py", line 22, in __call__
    return self.render()
  File "/joint/backend/eea-dx-cpanel-metadata/src/plone/restapi/services/__init__.py", line 21, in render
    content = self.reply()
  File "/joint/backend/eea-dx-cpanel-metadata/src/plone/restapi/services/vocabularies/get.py", line 48, in reply
    vocabulary = factory(self.context)
  File "/joint/backend/eea-dx-cpanel-metadata/eggs/plone.schemaeditor-2.1.0-py3.8.egg/plone/schemaeditor/fields.py", line 62, in FieldsVocabularyFactory
    if context.allowedFields is not None:
AttributeError: 'RequestContainer' object has no attribute 'allowedFields'
```

### PR DESCRIPTION
**Pull request by avoinea**
See #76

### CODE REVIEW

**Comment by avoinea** [comment]
@jenkins-plone-org please run jobs

**Comment by avoinea** [comment]
I'm afraid I don't know what's wrong with Jenkins :confused:

**Comment by avoinea** [comment]
@jenkins-plone-org please run jobs

**Comment by avoinea** [comment]
@jenkins-plone-org please run jobs

**Comment by avoinea** [comment]
Merged as Jenkins was finally green.

@mauritsvanrees 

Could you please do releases for `2.x` and `3.x` in order to be able update plone.restapi dependencies.

**Comment by mauritsvanrees** [comment]
I released 3.0.1 for 5.2 a week ago, and 2.1.1 for 5.1 just now .

**Pull request merged**
