### PR TITLE
Avoid a deprecation warning

### PR DESCRIPTION
**Pull request by gforcada**
For more than 9 years `ObjectEvent` is already on `zope.interface`:
https://github.com/zopefoundation/zope.interface/commit/22f5e01a85f4331141ba782ac96879193f32f59b

### CODE REVIEW

**Comment by gforcada** [comment]
Feel free to run the tests.

**Comment by jensens** [comment]
Thx! All fine, except a changelog entry is missing.

**Comment by gforcada** [comment]
A changelog entry to avoid a deprecation warning? Oh my, having an entry on the changelog about it seems too much of detail IMHO :shrug:

**Comment by jensens** [comment]
looks like @mauritsvanrees had the same idea and did not check existing PRs....

**Pull request closed without merging**
