### PR TITLE
port robot tests

### PR DESCRIPTION
**Pull request by 1letter**
This is part of https://github.com/plone/Products.CMFPlone/issues/3813

- update configuring with plone/meta
- port robot tests

### CODE REVIEW

**Comment by 1letter** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
Looks okay to me, but I don't know anything about playwright yet.

I have a problem though when I try it locally: `bin/test` hangs on the second test.  That is probably something general, so I will ask in the CMFPlone issue.

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by 1letter** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
The failing test is unrelated to this PR.

**Pull request merged**
