### PR TITLE
Fix schmaeditor to preserve i18n Message values

### PR DESCRIPTION
**Pull request by datakurre**
https://github.com/plone/plone.schemaeditor/pull/18 for master branch

### CODE REVIEW

**Comment by jensens** [comment]
needs rebase please

**Comment by datakurre** [comment]
rebased

**Comment by jensens** [comment]
http://jenkins.plone.org/view/All/job/pull-request/148/

**Comment by jensens** [comment]
one failure here http://jenkins.plone.org/view/All/job/pull-request/148/robot/report/robot_report.html#suites?s1-s29-s2

**Comment by datakurre** [comment]
@jensens Surprising. How to trigger test run again to be sure?

**Comment by jensens** [comment]
@datakurre go to http://jenkins.plone.org/view/All/job/pull-request/build - login and enter the url of this PR

**Comment by datakurre** [comment]
http://jenkins.plone.org/view/All/job/pull-request/157/

**Comment by datakurre** [comment]
Test failure persist, so it need to be checked and fixed before merge.

**Comment by datakurre** [comment]
http://jenkins.plone.org/view/All/job/pull-request/160/

**Comment by datakurre** [comment]
Green. Applied same patch for the 4.3 on, but not sure, what fails there.

**Comment by jensens** [comment]
http://jenkins.plone.org/view/All/job/pull-request/161/

**Comment by jensens** [comment]
seems to be green on this and for 4.3 #18 its not...

**Pull request merged**
