### PR TITLE
Add a "protected" method to IFieldFactory

### PR DESCRIPTION
**Pull request by ebrehault**
`protected()` will return `False` by default, but by overriding it in a custom subclass, we can get the same rendering as a behavior field (= not editable and not draggable) for any field we want.

### CODE REVIEW

**Comment by ebrehault** [comment]
@tisto how can I trigger a jenkins build to test this PR? (the page http://jenkins.plone.org/job/pull-request/ mentions I have to be logged in and to provide the PR url, but I do not see where I can enter the url)

**Comment by tisto** [comment]
You have to click the "Build with parameters" button.

**Comment by jensens** [comment]
http://jenkins.plone.org/view/All/job/pull-request/211/
- [ ] ok
- [ ] fails

**Comment by ebrehault** [comment]
@jensens the build you have launched use the sample PR (p.a.discussion).
I have launch a new one: http://jenkins.plone.org/job/pull-request/213/
- [ ] ok
- [ ] fail

**Comment by jensens** [comment]
hmm, ops.
@tisto, may you remove the default parameter in PR testing (p.a.discussion)? The description of the field says it anyway.

**Pull request merged**
