### PR TITLE
Display status message in parent window after modal close

### PR DESCRIPTION
**Pull request by ebrehault**
@vangheem @davisagli : it appears we could not safely remove modals here (too many technical + UI consequences). So here is my fix:
- messages that must be displayed in the parent window are produced using `Products.statusmessages`, messages that must appear in the modals are still produce using `self.status`,
- after adding or editing a field, we do not redirect to parent (that would burn the status messages), as the modal will reload the parent window anyway,
- we do not use the main template anymore to display add and edit forms, so it does not burn the `Products.statusmessages` messages.

@tisto, 2 bad news for you:
- we keep the modals,
- it does break the tests in p.a.users, p.a.dexterity and p.schemaeditor because it seems the BrowserTest requests cannot be adapted to create portal messages `IStatusMessage(self.request).addStatusMessage`, is there something special we must do?

### CODE REVIEW

**Comment by vangheem** [comment]
running jenkins job here(I think): http://jenkins.plone.org/job/pull-request-5.0/2/

**Comment by vangheem** [comment]
hhmm, plone.app.relationfield test errors. Related?

**Comment by ebrehault** [comment]
@tisto, reagrding this PR, I have fixed the tests in this package, but I also need to fix tests in others packages (p.a.dexterity and p.a.relationfield), so I would like Jenkins to test the all thing at once. Shall I create a specific .cfg in https://github.com/plone/buildout.coredev/tree/5.0/plips and it will be automatically processed by Jenkins or there is something to do on the Jenkins config side ?

**Comment by ebrehault** [comment]
@tisto, forget it, I will just add the needed branches in the existing p.a.users plip .cfg

**Comment by tisto** [comment]
Yeah. Just re-use the existing plip. Ping me if you need help.

**Comment by ebrehault** [comment]
@tisto: tests are ok http://jenkins.plone.org/view/PLIPs/job/plip-13350-edit-member-schema-ttw/30/
The failing test in plone.app.contenttypes is not related (memory error with robot...).
And the one in p.a.users is related but fixed with my last commit (forgot to push before launching Jenkins).

I have created the associated PR in p.a.dexterity and p.a.relationfield:
https://github.com/plone/plone.app.dexterity/pull/168
https://github.com/plone/plone.app.relationfield/pull/13

**Comment by tisto** [comment]
@ebrehault We have 11 new test failures:

http://jenkins.plone.org/view/PLIPs/job/plip-13350-edit-member-schema-ttw/31/

I guess we have to merge master branches into our feature branches again.

**Comment by ebrehault** [comment]
I have merged last Products.CMFPlone master commits in my branch. Test job: http://jenkins.plone.org/view/PLIPs/job/plip-13350-edit-member-schema-ttw/32/

**Comment by ebrehault** [comment]
@tisto, tests regarding this PR are fixed (we still have the known p.a.users test issues of course)

**Comment by tisto** [comment]
http://jenkins.plone.org/job/pull-request-5.0/50/

**Pull request merged**
